version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    networks:
      - network-tier

  backend:
    container_name: backend
    build: ./backend
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    environment:
      spring.datasource.url: "jdbc:mysql://mysqldb:3306/test_db?useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true"
    volumes:
      - ./backend:/backend
    networks:
      - network-tier
    tty: true

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_ROOT_HOST: "%"
      CHARACTER_SET_SERVER: utf8
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]
    volumes:
      - mysql-data:/var/lib/menucanvas
    ports:
      - "3306:3306"

    networks:
      - network-tier
    platform: linux/amd64

networks:
  network-tier:
    external: true

volumes:
  mysql-data:
